### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by SunYongchao** [josephchenhk/qtrader#1]
When I try to run your demo, I got the error "No module named 'futu'". I find that futu_gateway.py import futu file, which is the file contains futu_gateway.py. Is there any problem of this usage? Or how can I fix this error? Thanks.

**Comment by josephchenhk** [comment]
> When I try to run your demo, I got the error "No module named 'futu'". I find that futu_gateway.py import futu file, which is the file contains futu_gateway.py. Is there any problem of this usage? Or how can I fix this error? Thanks.

Hi, you need to install futu-api first,` $ pip install futu-api`, hope it helps. Thanks.

**Comment by SunYongchao** [comment]
> > When I try to run your demo, I got the error "No module named 'futu'". I find that futu_gateway.py import futu file, which is the file contains futu_gateway.py. Is there any problem of this usage? Or how can I fix this error? Thanks.
> 
> Hi, you need to install futu-api first,` $ pip install futu-api`, hope it helps. Thanks.

Thanks a lot and my problem is solved.

**Comment by josephchenhk** [comment]
> > > When I try to run your demo, I got the error "No module named 'futu'". I find that futu_gateway.py import futu file, which is the file contains futu_gateway.py. Is there any problem of this usage? Or how can I fix this error? Thanks.
> > 
> > 
> > Hi, you need to install futu-api first,` $ pip install futu-api`, hope it helps. Thanks.
> 
> Thanks a lot and my problem is solved.

Good to hear that. As such I will close this issue.
