### ISSUE TITLE
DemoStrategy的init_strategy_cash参数是不是有问题，报错了。

### ISSUE THREAD

**Issue by Junffzz** [josephchenhk/qtrader#21]
class DemoStrategy(BaseStrategy):
    """Demo strategy"""

    def __init__(self,
                 securities: Dict[str, List[Stock]],
                 strategy_account: str,
                 strategy_version: str,
                 init_strategy_cash: Dict[str, float],
                 engine: Engine,
                 **kwargs
                 ):
        super().__init__(
            securities=securities,
            strategy_account=strategy_account,
            strategy_version=strategy_version,
            engine=engine,
            init_strategy_cash=init_strategy_cash,
            **kwargs
        )

这个参数init_strategy_cash在 super().__init__报错了，在父类中参数换了麻烦作者改下。

**Comment by josephchenhk** [comment]
> class DemoStrategy(BaseStrategy): """Demo strategy"""
> 
> ```
> def __init__(self,
>              securities: Dict[str, List[Stock]],
>              strategy_account: str,
>              strategy_version: str,
>              init_strategy_cash: Dict[str, float],
>              engine: Engine,
>              **kwargs
>              ):
>     super().__init__(
>         securities=securities,
>         strategy_account=strategy_account,
>         strategy_version=strategy_version,
>         engine=engine,
>         init_strategy_cash=init_strategy_cash,
>         **kwargs
>     )
> ```
> 
> 这个参数init_strategy_cash在 super().__init__报错了，在父类中参数换了麻烦作者改下。

谢谢提醒，我更新了例子的代码，现在应该可以了。

**Comment by josephchenhk** [comment]
Updated the demo example
