### ISSUE TITLE
data.py文件报错AttributeError: 'tuple' object has no attribute 'date'

### ISSUE THREAD

**Issue by Junffzz** [josephchenhk/qtrader#22]
File "/qtrader/core/data.py", line 110, in _get_data
    if start.date() <= dt <= end.date():
AttributeError: 'tuple' object has no attribute 'date'

这是报错，我使用的是python3.10版本，不知道是不是版本问题

**Comment by Junffzz** [comment]
找到问题了，不用解答，谢谢

**Comment by josephchenhk** [comment]
Ok, I close it now as this seems not be an issue. Feel free to re-open it if you still have the problem.
