### ISSUE TITLE
mac环境修改了main_demo还是跑不起来，是不是缺少了哪个步骤

### ISSUE THREAD

**Issue by Junffzz** [josephchenhk/qtrader#23]
Duplicate key in file PosixPath('/Users/ZhaoJunfeng/miniconda3/envs/zjfenv/lib/python3.10/site-packages/matplotlib/mpl-data/matplotlibrc'), line 406 ('axes.unicode_minus: True  # use Unicode for the minus symbol rather than hyphen.  See')
Traceback (most recent call last):
  File "/Users/ZhaoJunfeng/workspace/python/qtrader/examples/demo_strategy/main_demo.py", line 27, in <module>
    from qtrader.core.event_engine import BarEventEngineRecorder, BarEventEngine
ModuleNotFoundError: No module named 'qtrader.core.event_engine'

**Comment by Junffzz** [comment]
Traceback (most recent call last):
  File "/Users//python/qtrader/examples/demo_strategy/main_demo.py", line 27, in <module>
    from qtrader.core.event_engine import BarEventEngineRecorder, BarEventEngine
ImportError: dlopen(/Users/python/qtrader/qtrader/core/event_engine.so, 2): Symbol not found: __Py_CheckRecursionLimit
  Referenced from: /Users/python/qtrader/qtrader/core/event_engine.so
  Expected in: flat namespace
 in /Users/python/qtrader/qtrader/core/event_engine.so

 git拉下来的源码，重命名了engine和event_engine运行还是报错

**Comment by josephchenhk** [comment]
please use python=3.8 and try again.
