### ISSUE TITLE
插件analysis的plot_pnl_with_category方法有示例数据吗

### ISSUE THREAD

**Issue by Junffzz** [josephchenhk/qtrader#24]
记录添加如下参数，包括了action    
recorder = BarEventEngineRecorder(datetime=[],
                                      action=[],
                                      open=[],
                                      high=[],
                                      low=[],
                                      close=[],
                                      volume=[])
但是生成的action数据还是解析失败。
生成的csv记录如下：
datetime,portfolio_value,action,close,high,low,open,strategy_portfolio_value,volume
2020-05-14,99950.01994,"{'side': 'LONG', 'offset': 'OPEN', 'sec': 'PDD'}|",[60.84],[61.0],[57.35],[58.38],99950.01994,[6802171]
但是action列的数据好像不对。
调用这个方法生成的。
self.update_action
麻烦大哥帮忙解答一下

**Comment by josephchenhk** [comment]
你好，请问报错信息是什么？

**Comment by Junffzz** [comment]
> 你好，请问报错信息是什么？

已经解决，谢谢

**Comment by josephchenhk** [comment]
Ok, close the thread as it resolved.
