### ISSUE TITLE
为什么gateways要支持多个gateway

### ISSUE THREAD

**Issue by Junffzz** [josephchenhk/qtrader#26]
engine = Engine(gateways={gateway_name: gateway}) 中的gateways参数为什么是字典，要满足一个策略同时跑多个平台吗

**Comment by josephchenhk** [comment]
> engine = Engine(gateways={gateway_name: gateway}) 中的gateways参数为什么是字典，要满足一个策略同时跑多个平台吗

是的。跨平台策略比如套利等策略，需要同时支持多个交易通道。

**Comment by Junffzz** [comment]
> > engine = Engine(gateways={gateway_name: gateway}) 中的gateways参数为什么是字典，要满足一个策略同时跑多个平台吗
> 
> 是的。跨平台策略比如套利等策略，需要同时支持多个交易通道。

了解了，谢谢
