### ISSUE TITLE
No module named 'func_timeout'

### ISSUE THREAD

**Issue by 10sun** [josephchenhk/qtrader#3]
Hi Joseph, thank you very much for sharing this repo.

While trying to run the main_demo.py, I ran into an error while importing the BarEventEngineRecorder, BarEventEngine from qtrader.core.event_engine. It says 'No module named func_timeout'. Any idea of a potential reason?

many thanks!

**Comment by josephchenhk** [comment]
Hi, did you install via pip or Github? I do not update pip frequently, therefore currently it is better to install via Github:

`pip install git+https://github.com/josephchenhk/qtrader@master`

Please let me know if the issue still exists?

**Comment by josephchenhk** [comment]
I will close this issue. If you still have the problem, please feel free to re-open it. Thank you!
